### ISSUE TITLE
解析微信url code 格式丢失

### ISSUE THREAD

**Issue by t1ger** [henix/get-article-release#1]
执行命令无报错，解析完成后查看code格式丢失
测试网址　https://mp.weixin.qq.com/s/ikOGdlZVu0xDhH_ZupZadQ

**Comment by henix** [comment]
谢谢反馈！代码的样式确实是有问题。我会择机修复。

顺便一问，你使用的是 Win / Linux 的命令行 / GUI 的哪个版本？

**Comment by t1ger** [comment]
Linux 的命令行  
Operating System: Ubuntu 20.04.5 LTS
Kernel: Linux 5.4.0-144-generic
Architecture: x86-64

**Comment by henix** [comment]
已在 v1.0.2 版本中修复了这个问题，请到 https://lab.henix.info/get-article.html 重新下载

之前已保存的文章需要重新保存
